/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Chair(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/models/Chair.glb");
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Chair.geometry} material={materials.Chair} />
        </group>
    );
}

useGLTF.preload("/Chair.glb");
