/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

const Chair = React.forwardRef(({ props, ref }) => {
  const { nodes, materials } = useGLTF("/models/Chair.glb");
  const [box] = useBox(() => ({args: [2, 2, 2], position: [0, 1, 0], type: "Static"}));
  return (
    <mesh ref={box} castShadow={true} >
    <boxGeometry args={[1, 1, 1]} />
    <meshStandardMaterial color={"white"} />
</mesh>
  );
});

export default Chair;

useGLTF.preload("/Chair.glb");
