/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CoffeeTable(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/CoffeeTable.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.04}>
        <mesh
          geometry={nodes["10222_Coffee_Table_v1_max2010vb_1"].geometry}
          material={materials["10222_Coffee_Table_v1"]}
        />
        <mesh
          geometry={nodes["10222_Coffee_Table_v1_max2010vb_2"].geometry}
          material={materials["10222_Coffee_Table_v1_glass"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/CoffeeTable.glb");
