/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useState } from "react";

export default function Hair(props) {
  const [eyeStyle, setEyeStyle] = useState(null);

  const group = useRef();
  const { nodes, materials } = useGLTF("/Models/Character.glb");

  useEffect(() => {
    switch (props.eyeStyle) {
      case 1:
        setEyeStyle(materials["Eye 1"]);
        break;
      case 2:
        setEyeStyle(materials["Eye 2"]);
        break;

      default:
        setEyeStyle(materials["Eye 1"]);
        break;
    }
  }, [materials, props.eyeStyle]);

  return (
    <group ref={group} {...props} dispose={null} scale={[2, 2, 2]}>
      <skinnedMesh
        geometry={nodes.Cube001_1.geometry}
        skeleton={nodes.Cube001_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube001_2.geometry}
        material={eyeStyle}
        skeleton={nodes.Cube001_2.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/Character.glb");
