/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import {useGLTF} from "@react-three/drei";
import {useCustomGLTF} from "../../helpers/utilities";
import {useBox} from "@react-three/cannon";

const IndoorTree = function (props) {
    const {nodes, materials, boundingBox, meshPosition} = useCustomGLTF("/models/IndoorTree.glb")

    const [box, api] = useBox(() => ({
        args: [boundingBox.max.x - boundingBox.min.x, boundingBox.max.y - boundingBox.min.y, boundingBox.max.z - boundingBox.min.z],
        position: [0, 0, 0],
    }));

    return (
        <group ref={box} {...props}>
            <group position={[-2,-2,-2]}>
                <mesh geometry={nodes.Shape_IndexedFaceSet.geometry} material={materials.MA_IDP_root}/>
                <mesh geometry={nodes.Shape_IndexedFaceSet001.geometry} material={materials.MA_IDP_ground}/>
                <mesh geometry={nodes.Shape_IndexedFaceSet002.geometry} material={materials.MA_IDP_leaves}/>
                <mesh geometry={nodes.Shape_IndexedFaceSet003.geometry} material={materials.MA_IDP_Pot}/>
            </group>
        </group>
    );
}

export default IndoorTree;

useGLTF.preload("/IndoorTree.glb");
