/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const ModernTable = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/models/ModernTable.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
});

export default ModernTable;

useGLTF.preload("/ModernTable.glb");
