/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { usePlane } from "@react-three/cannon";

export default function Office(props) {
  const group = useRef();

  const { nodes, materials } = useGLTF("/models/Office.glb");
  return (
    <mesh position={[5,0,5]}>
      <planeGeometry args={[1000, 1000]} />
    </mesh>
  );
}

useGLTF.preload("/Office.glb");
