/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Office(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/models/Office.glb");
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Cube_1.geometry} material={materials.Floor} />
            <mesh geometry={nodes.Cube_2.geometry} material={materials.Walll} />
        </group>
    );
}

useGLTF.preload("/Office.glb");
