/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { usePlane } from "@react-three/cannon";

export default function Office(props) {
  const group = useRef();
  const [ref] = usePlane(() => ({
    position: [0, 1, 0],
    type: "Static"
  }))
  const { nodes, materials } = useGLTF("/models/Office.glb");
  return (
    <mesh ref={ref} >
      <group ref={group} {...props} dispose={null}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Walll} />
      </group>
    </mesh>
  );
}

useGLTF.preload("/Office.glb");
