/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useCustomGLTF} from "../../helpers/utilities";
import {useBox} from "@react-three/cannon";

export default function Model(props) {
  const { nodes, materials, boundingBox, meshPosition } = useCustomGLTF('/models/SofaChair.glb')

  const [box, api] = useBox(() => ({
    args: [boundingBox.max.x - boundingBox.min.x, boundingBox.max.y - boundingBox.min.y, boundingBox.max.z - boundingBox.min.z],
    position: [0,0,0],
  }));

  return (
    <group ref={box} {...props} dispose={null}>
      <mesh
        geometry={nodes.Chair.geometry}
          material={nodes.Chair.material}
        scale={[0.75, 0.15, 0.75]}>
        <mesh
          geometry={nodes.BezierCurve001.geometry}
          material={materials.Metal}
          position={[0, -1.45, -0.23]}
          rotation={[0, 1.54, 0]}
          scale={[0.85, 4.2, 0.85]}
        />
        <mesh
          geometry={nodes.Cube069.geometry}
          material={nodes.Cube069.material}
          position={[1.15, 4.91, 0]}
          scale={[0.17, 5.26, 0.91]}
        />
        <group position={[0, -1.02, 0]} scale={[0.23, 0.75, 0.23]}>
          <mesh geometry={nodes.Cylinder003.geometry} material={materials['Steel Black Polished']} />
          <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Steel White']} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/SofaChair.glb')
