/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/models/Test.glb");
    const { head, ...rest } = props;
    return (
        <group ref={group} {...rest} dispose={null}>
            {head === "box" ? (
                <mesh geometry={nodes.Box.geometry} material={nodes.Box.material} />
            ) : (
                <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} />
            )}
        </group>
    );
}

useGLTF.preload("/models/Test.glb");
