/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function YellowChair(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/YellowChair.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.3, 0]} rotation={[0, -1.57, 0]} scale={[0.86, 1.02, 0.86]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/YellowChair.glb')
